name: Create and Update Storage Bucket

on:
  push:
    branches:
      - main
    paths:
      - 'bucket/**'

jobs:
  terraform-docker-job:
    name: Run Terraform and Docker Tasks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Docker version
        run: docker --version

      - name: Get Access Key Json file
        env:
          ENCODED_ACCESS_KEY_JSON: ${{ secrets.ENCODED_ACCESS_KEY_JSON }}
        run: mkdir -p bucket/terraform/files echo $ENCODED_ACCESS_KEY_JSON | base64 -di > ./bucket/terraform/files/access-key.json 

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./bucket/terraform

      - name: Terraform Format Check
        run: terraform fmt -recursive
        working-directory: ./bucket/terraform

      - name: Terraform Plan
        run: terraform plan -lock=false
        working-directory: ./bucket/terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./bucket/terraform
