name: Create Infra and Update Images

on:
  push:
    branches:
      - main
    paths:
      - 'terraform/**'
      - 'golang-hello-globo'
      - 'python-hello-globo'

jobs:
  terraform-docker-job:
    name: Globo Case Runner
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.12.2

      - name: Docker version
        run: docker --version

      - name: Get Acces Key Json file
        env:
          ENCODED_ACCESS_KEY_JSON: ${{ secrets.ENCODED_ACCESS_KEY_JSON }}
        run: mkdir -p terraform/files && touch ./terraform/files/access-key.json  && echo $ENCODED_ACCESS_KEY_JSON | base64 -di > ./terraform/files/access-key.json 

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./terraform

      - name: Terraform Format Check
        run: terraform fmt -recursive
        working-directory: ./terraform

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./terraform

      - name: Terraform Apply
        run: terraform apply -auto--auto-approve
        working-directory: ./terraform
